config/routes.rb
Dmec711::Application.routes.draw do
  root to: 'home#home'

  resources :sessions, only: [:new, :create, :destroy]
  resources :therapists
  resources :therapy
  resources :agenda
  resources :client
  resources :colleague

  match '/home',  to: 'home#home'
  match '/clients',  to: 'client#index'
  match '/client/:id',  to: 'client#show'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/client/ajax_show/(:id)', to: 'client#ajax_show', via: :get

end

app/models/client.rb
class Client < ActiveRecord::Base
 # attr_accessible :name
 has_one :dossier
 has_many :notes
 has_many :clients_therapies
 has_many :therapies, :through => :clients_therapies
end

app/models/clients_therapies.rb
class ClientsTherapies < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :clients
  has_many :therapies
end

app/models/dossier.rb
class Dossier < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :dossier_items
  belongs_to :client
end

app/models/dossier_item.rb
class DossierItem < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :dossiers
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :therapy

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :name, :description, :client_id
  belongs_to :client

end

app/models/therapist.rb
class Therapist < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  has_many :therapies
  has_many :therapist_clients
  has_many :clients, :through => :therapist_clients

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true, format:     { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/therapist_client.rb
class TherapistClient < ActiveRecord::Base
  # attr_accessible :title, :body
  #has_many :clients
  #has_many :therapists
  belongs_to :client
end

app/models/therapy.rb
class Therapy < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :exercises
  belongs_to :therapist

end

app/controllers/agenda_controller.rb
class AgendaController < ApplicationController

  before_filter :signed_in_user

  def index

  end

end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  def index
    @clients = Client.all()
    @therapist = Therapist.find(current_user.id)
  end

  def show
    @client = Client.find(params[:id])
    @dossiers = @client.dossier
    @notes = @client.notes
    @clients = Client.all()
    @therapist = Therapist.find(current_user.id)
  end

  def ajax_show
    @client = Client.find(params[:id])
    @dossiers = @client.dossier

    @notes = @client.notes
    @clients = Client.all()
    @therapist = Therapist.find(current_user.id)

    view_data = render_to_string(:partial => 'client/ajax_show', :content_type => 'text/html')
    respond_to do |format|
      format.json { render :json => {
          :client => @client, :html => view_data
        }
      }
    end
  end
end

app/controllers/colleague_contoller.rb
class ColleagueController < ApplicationController
  def index

  end
end

app/controllers/dossier_controller.rb
class DossierController < ApplicationController

  def show
    @client = Client.find(params[:id])
    @dossier = @client.dossier.find(params[:dossier])
  end

  def new
    @dossier = Dossier.find(params[:dossier])
    # nog toevoegen
  end

  def edit
    @dossier = Dossier.find(params[:dossier])
    # nog toevoegen
  end

  def update
    @dossier = Dossier.find(params[:dossier])
    # nog toevoegen
  end

  def delete
    @dossier = Dossier.find(params[:dossier])
    @dossier.destroy
  end

  def create
    @dossier = Dossier.find(params[:dossier])
    # nog toevoegen
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :signed_in_user

  def index

  end

  def home

  end

end

app/controllers/note_controller.rb
class NoteController < ApplicationController

  def show
    @client = Client.find(params[:client])
    @note = Notes.find(params[:note])
  end

  def new
    @client = Client.find(params[:client])
    # nog toevoegen
  end

  def edit
    @client = Client.find(params[:client])
    @note = Note.find(params[:note])
    # nog toevoegen
  end

  def update
    @client = Client.find(params[:client])
    @note = Note.find(params[:note])
    # nog toevoegen
  end

  def delete
    @client = Client.find(params[:client])
    @note = Note.find(params[:note])
    @note.destroy
  end

  def create
    @client = Client.find(params[:client])
    # nog toevoegen
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = Therapist.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_back_or user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = Therapist.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_back_or user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/therapy_controller.rb
class TherapyController < ApplicationController
  def index
     @therapies = Therapy.all
  end

  def show
     @therapy = Therapy.find(params[:therapy])
  end

  def edit

  end

  def update

  end

  def delete

  end

  def new

  end

  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Wikitherapist"
    return base_title if page_title.empty?
    return "#{base_title} | #{page_title}"
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= Therapist.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= Therapist.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/views/agenda/index.html.erb
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li><a href="home">Home</a> </li>
    <li class="active"><a href="agenda">Agenda</a></li>
    <li><a href="client">Cliënten</a></li>
    <li><a href="therapy" data-toggle="tab">Therapieën</a></li>
    <li><a href="colleague" data-toggle="tab">Collega's</a></li>
  </ul>

  <div class="page-header well">
    <div class="tabbable"> <!-- Only required for left/right tabs -->
      <ul class="nav nav-tabs" id="clients_tabs">
        <li><a href="#week40" data-toggle="tab">Week 40</a></li>
        <li><a href="#week41" data-toggle="tab">Week 41</a></li>
        <li class="active"><a href="#week42" data-toggle="tab">Week 42</a></li>
      </ul>
      <div class="tab-content" id="clients_tabs_content">
        <div class="tab-pane" id="week40">
          <p>Week 40</p>
        </div>
        <div class="tab-pane" id="week41">
          <p>Week 41</p>
        </div>
        <div class="tab-pane active" id="week42">
          <p>Week 42 is vet cool</p>
        </div>


    <ul class="thumbnails">
      <li class="">
        <a href="<%= client_path(1) %>" class="thumbnail">
          <%= image_tag("Agenda.png") %>
        </a>
      </li>
    </ul>
      </div>
    </div>
  </div>
</div>

app/views/home/home.html.erb
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="home">Home</a></li>
    <li><a href="agenda">Agenda</a></li>
    <li><a href="client">Cliënten</a></li>
    <li><a href="therapy">Therapieën</a></li>
    <li><a href="colleague">Collega's</a></li>
  </ul>

  <div class="page-header well">
    <h2>Home</h2>
  </div>
</div>

app/views/home/index.html.erb
<% if signed_in? %>
    <%= yield() %>
<% else %>
    <div class="center hero-unit">
      <h1>Welcome to the Sample App</h1>

      <h2>
        This is the home page for the
        <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
      </h2>

      <%= link_to "Sign up now!", signup_path,
                  class: "btn btn-large btn-primary" %>
    </div>

    <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>